sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t vaib79/udemy-docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true vaib79/udemy-docker-react npm run test
